name: Docker Action Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Docker action
        id: docker-action
        uses: ./.github/actions/docker-action
        with:
          who-to-greet: 'GitHub User'

      - name: Get the output from Docker action
        run: echo "Hello, ${{ steps.docker-action.outputs.who-to-greet }}! The time from Docker action was ${{ steps.docker-action.outputs.time }}"