name: JS Action Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Custom Action from External Repo
      id: custom-action
      uses: mcritic/m-actions/.github/actions/js-action@v1.0.0
      with:
        who-to-greet: 'External GitHub User'

    - name: Print the Time
      run: echo "The current time is ${{ steps.custom-action.outputs.time }}"
